version: '3'

services:
  shopware:
    build: ./public/container/php
    ports:
    - "8080:80"
    volumes:
    - ./public/shopware:/var/www/html:cached
    container_name: shopware-container
    links:
    - mysql:mysql

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: app
      MYSQL_PASSWORD: app
